---
:concurrency: <%= ENV.fetch('SIDEKIQ_CONCURRENCY', 10) %>
:queues:
  # Prioritize mail delivery to keep user-facing flows snappy
  - [mailers, 3]
  # General-purpose app jobs
  - [default, 2]
  # Background cache/report warmers and heavier aggregations
  - [reports, 1]
